# This workflow generates the output and pushes it to master branch

name: Grab dat joke

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    - name: Run joke_grabber.sh
      run: ./joke_grabber.sh

    - name: Push to master branch
      uses: Automattic/action-commit-to-branch@master
      with:
        branch: 'master'
        commit_message: 'GitHub Actions Build master'
      env:
        GITHUB_TOKEN: ${{ secrets.MAXIMELAFARIE_DEPLOY_KEY }} # Required